
name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:  # üîí Asegura permisos para SonarCloud bot
  contents: read
  pull-requests: write  # üëà Necesario para comentar en la PR

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para PRs para que SonarCloud pueda comparar commits

      # SonarCloud initialization (con argumentos del proyecto)
      - name: SonarCloud Init
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=sara-prueba
            -Dsonar.projectKey=vjp-saraMG_curso_symfony_5_primeros_pasos
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Escaneo real del c√≥digo
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
